# Generated by Django 4.2.5 on 2023-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_favorite_by_remove_review_reviewer'),
        ('authentication', '0002_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_book',
            field=models.ManyToManyField(blank=True, to='book.book'),
        ),
    ]
