# Generated by Django 4.2.5 on 2023-10-02 10:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_remove_review_pub_date_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
