# Generated by Django 4.2.5 on 2023-10-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorite',
        ),
    ]
