# Generated by Django 4.2.5 on 2023-10-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_favorite_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorite_by',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
    ]
