# Generated by Django 4.2.5 on 2023-10-27 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0013_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/book'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'reviewer')},
        ),
    ]
